language: ruby
cache: bundler
rvm:
#  - rbx-3
  - ruby-2.2
  - ruby-2.3.0
  - ruby-2.3.1

addons:
  code_climate:
    repo_token: a653e3a741027378cdb00f4f99f598ed3de962de0ef5eaf4c88f262a1e664f91

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1e23820a996c9242342e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libtag1-dev

bundler_args: --without production development doc

